# Generated by Django 5.0.4 on 2024-04-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_contact_phone_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
